spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: ${RDS_DATABASE_URL}
    username: ${RDS_DATABASE_USERNAME}
    password: ${RDS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
config:
  domain: ${AWS S3 Endpoint}
logging:
  level:
    server.petching: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true