# This is a basic workflow to help you get started with Actions
name: Build and Deploy Spring Boot to AWS EC2
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: petching.link
  CODE_DEPLOY_APPLICATION_NAME: petching-client-codeDeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: petching-client-codeDeploy-group


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
